### ISSUE TITLE
Add function to parse housekeeping data

### ISSUE THREAD

**Issue by aidenszeto** [staynomad/admin-dashboard#16]
The backend returns housekeeping data in the following format:
![image](https://user-images.githubusercontent.com/66970460/119595540-9190e880-bd92-11eb-9633-dce0236f735a.png)

The graph, however, expects the data to be in this format:
![image](https://user-images.githubusercontent.com/66970460/119595506-86d65380-bd92-11eb-918d-d87527edeb19.png)

We want to convert the first format into the second format

**Comment by MikePodo** [comment]
Completed. Will be included in user-graphs branch merge.
